<!DOCTYPE html>
<html lang="fr" class="h-100">
<!-- HEAD -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP - MVC</title>
    <link rel="stylesheet" href="./assets/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        main {
            margin-top: 56px;
        }

        #conv {
            margin-top: 79px;
        }
    </style>

</head>

<!-- BODY -->
<body class="d-flex flex-column h-100">
    <!-- HEADER START -->
    <header>
        <nav class="navbar navbar-expand-lg bg-body-secondary fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="?page=home">BestImages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <?php foreach(CONFIG_ROUTES as $key => $value) : ?>
                        <?php if($key !== "details" && $key !== "search" && $key !=="addimage" && $key !=="admin") :?>
                        <li class="nav-item">
                            <a class="nav-link <?php if($key === $page) echo 'active'?>" href="?page=<?= $key ?>"><?= ucfirst($key) ?></a>
                        </li>
                        <?php endif ?>
                    <?php endforeach ?>
                    <form class="d-flex mx-3" role="search" method="GET">
                            <input type="hidden" value="search" name="page">
                            <input class="form-control me-2" type="search" placeholder="Chercher" aria-label="Search" name="query">
                            <button class="btn btn-outline-success" type="submit">Chercher</button>
                    </form>
                    </ul>
                    <?php if(!isset($_SESSION['user_info'])) : ?>
                        <a class="btn btn-outline-primary mx-1" href="?page=register">S'inscrire</a>
                        <a class="btn btn-outline-secondary mx-1" href="?page=signin">Se connecter</a>
                    <?php endif ?>
                    <?php if(isset($_SESSION['user_info'])) : ?>
                        <a class="btn btn-outline-tertiary" href="?page=profile">
                            <?= $_SESSION['user_info']['first_name'].' '.$_SESSION['user_info']['last_name'] ?>
                        </a>
                        <?php if(isset($_SESSION['user_info']) && $_SESSION['user_info']['role'] != "user") : ?>
                            <a class="btn btn-<?= $_SESSION['user_info']['role'] == "admin" ? "warning":"success" ?> mx-1" href="?page=admin">
                                <?= $_SESSION['user_info']['role'] == "admin" ? "Admin":"Mes publications"; ?>
                            </a>
                        <?php endif ?>

                        <a class="btn btn-outline-secondary mx-1" href="?page=signout">Se déconnecter</a>
                    <?php endif ?>
                </div>
            </div>
        </nav>
    </header>
    <!-- HEADER END -->

    <!-- MAIN START -->
    <main class="flex-shrink-0">
    <?php
        include "./views/template_".$page.".phtml";
    ?>
    </main>
    <!-- MAIN END -->

    <!-- FOOTER START -->
    <footer class="bg-body-secondary footer mt-auto p-3">
        <section class="container-fluid text-center">
            &copy; DWWM_2023
        </section>

    </footer>
    <!-- FOOTER END -->

    <!-- SCRIPT BOOTSTRAP -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>