<section class="position-fixed d-flex align-items-center p-3 gap-3 w-100 z-3 text-bg-secondary">
    <a href="?page=mailbox" class="btn btn-primary">Retour messagerie</a>
    <h4 id="convTitle"></h4>
</section>

<section class="container-fluid d-flex flex-column" id="conv">
</section>

<div class="mt-3 container-fluid">
    <div class="form-floating">
        <textarea class="form-control" placeholder="Leave a comment here" id="message" name="message"></textarea>
        <label for="message">Votre message</label>
    </div>
    <button class="btn btn-success mt-2 mb-2" id="sendBtn">Envoyer</button>
</div>


<script>
    // DOM var
    let convTitle = document.querySelector('#convTitle');
    let convBlock = document.querySelector('#conv');
    let messageInput = document.querySelector('#message');
    let sendBtn = document.querySelector('#sendBtn');

    // Data var
    const months = ['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];
    let conversation = [];

    // Display
    async function displayConv() {

        await fetch('?page=getconv&user=<?= $_SESSION['user_info']['id'] ?>&person=<?= $_GET['person']?>')
        .then(response => response.json())
        .then(data => conversation = data)
        .catch(error => console.error("Error :", error));
        
        convTitle.textContent = `Votre conversation avec ${conversation.friend.first_name} ${conversation.friend.last_name}`;

        while (conversation.messages.length > convBlock.children.length) {
            // Create card
            const card = document.createElement('div');
            convBlock.appendChild(card);
            card.classList.add('card','mb-2', `align-self-${conversation.user.id == conversation.messages[convBlock.children.length-1].id_sender ? 'end':'start'}`,`text-bg-${conversation.user.id == conversation.messages[convBlock.children.length-1].id_sender ? 'primary':'secondary'}`,'rounded-pill','px-3','py-0');

            // Create card body
            const cardBody = document.createElement('div');
            cardBody.classList.add('card-body');
            card.appendChild(cardBody);

            // Create card content
            const cardContent = document.createElement('p');
            cardContent.classList.add('card-text');
            cardBody.appendChild(cardContent);
            let date = new Date(conversation.messages[convBlock.children.length-1].date_sent);
            date = `${date.getDate()} ${months[date.getMonth()]} ${date.getFullYear()} à ${date.getHours() < 10 ? "0":""}${date.getHours()}:${date.getMinutes() < 10 ? "0":""}${date.getMinutes()}`;
            cardContent.innerHTML = `
                <strong> ${conversation.user.id == conversation.messages[convBlock.children.length-1].id_sender ? "Moi":conversation.friend.first_name} - </strong>
                ${conversation.messages[convBlock.children.length-1].message}<br>
                <small>le ${date}</small>`  
                
            // go to end of page
            window.scrollTo(0, document.body.scrollHeight);
        }

    };
    setInterval(displayConv, 500);



    // Post
    async function postMessage(e) {
        e.preventDefault();
        if(messageInput.value.trim() != "") {
            let message = {
                'id_sender': "<?= $_SESSION['user_info']['id'] ?>",
                'id_receiver': "<?= $_GET['person'] ?>",
                'message': messageInput.value
            }          
    
            await fetch('?page=sendmessage', {
                method: "POST",
                headers: {
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(message),
            })
            .catch(error => console.error("Error :", error));

            messageInput.value = "";
        }
    }    
    
    sendBtn.addEventListener('click', postMessage);
</script>