<div class="container-fluid row d-flex justify-content-between px-2">
    <section class="mt-3 col-3">
        <div class="position-fixed col-3">
            <h4>Vos conversations</h4>
            <?php foreach($convInfos as $c) : ?>
                <a href="?page=messages&conv=<?= $c[1]['id_conv']?>" class="text-decoration-none"><div class="card mb-3 p-3 w-100">
                    <div><strong><?php 
                        $names = "";                 
                        foreach($c[0] as $name) {
                            if(empty($names)) { $names .= $name; }
                            else { $names .=', '.$name; }
                        }
                        echo $names;
                    ?></strong></div>
                    <div>
                        <?= $c[1]['message']; ?>                
                    </div>
                </div></a>
            <?php endforeach; ?>
            <a href="?page=newconv" class="btn btn-success">Nouvelle conversation</a>
        </div>
      

    </section>

    <section class="col-8">
        <div class="position-fixed d-flex align-items-center p-3 gap-3 z-3 text-bg-secondary mt-1 rounded">
            <h4 id="convTitle"></h4>
        </div>
        <div class="container-fluid d-flex flex-column" id="conv">
        </div>
        <div class="mt-3 container-fluid">
            <div class="form-floating">
                <textarea class="form-control" placeholder="Leave a comment here" id="message" name="message"></textarea>
                <label for="message">Votre message</label>
            </div>
            <button class="btn btn-success mt-2 mb-2" id="sendBtn">Envoyer</button>
        </div>
    </section>
</div>



<script>
    // DOM var
    let convTitle = document.querySelector('#convTitle');
    let convBlock = document.querySelector('#conv');
    let messageInput = document.querySelector('#message');
    let sendBtn = document.querySelector('#sendBtn');

    // Data var
    const months = ['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];
    let conversation = [];
    let conversationPanel = [];
    let userId = <?= $_SESSION['user_info']['id'] ?>;

    // Display all conversations
    (async function displayAllConv() {
        await fetch('?page=getallconvs&id=<?= $_SESSION['user_info']['id'] ?>')
        .then(response => response.json())
        .then(data => conversationPanel = data)
        .catch(error => console.error("Error :", error));

    })();

    // Display conversation
    async function displayConv() {

        // Récupérer les data
        await fetch('?page=getconv&conv=<?= $_GET['conv'] ?>')
        .then(response => response.json())
        .then(data => conversation = data)
        .catch(error => console.error("Error :", error));

        // Construire le titre de la conversation
        if(convTitle.textContent.length == 0) {
            let friends = ``;
            for(user of conversation.users) {
                if(user.id != userId) {
                    friends += friends.length == 0 ? '':', ';
                    friends += `${user.first_name} ${user.last_name}`;
                }
            }
            convTitle.textContent = `Votre conversation avec ${friends}`; 
        }        

        // Construire la page
        while (conversation.messages.length > convBlock.children.length) {
            // Create card
            const card = document.createElement('div');
            convBlock.appendChild(card);
            let currentMessage = conversation.messages[convBlock.children.length-1];
            card.classList.add('card','mb-2', `align-self-${userId == currentMessage.id_sender ? 'end':'start'}`,`text-bg-${userId == currentMessage.id_sender ? 'primary':'secondary'}`,'rounded','px-3','py-0');

            // Create card body
            const cardBody = document.createElement('div');
            cardBody.classList.add('card-body');
            card.appendChild(cardBody);

            // Create card content
            const cardContent = document.createElement('p');
            cardContent.classList.add('card-text');
            cardBody.appendChild(cardContent);
            
            // Préparer la date
            let date = new Date(currentMessage.date_sent);
            date = `${date.getDate()} ${months[date.getMonth()]} ${date.getFullYear()} à ${date.getHours() < 10 ? "0":""}${date.getHours()}:${date.getMinutes() < 10 ? "0":""}${date.getMinutes()}`;
            
            // Préparer le nom de l'utilisateur qui écrit le message
            let name = ``;
            for(user of conversation.users) {
                if(currentMessage.id_sender == user.id) {
                    name = user.first_name;
                }
            }

            cardContent.innerHTML = `
                <strong> ${userId == currentMessage.id_sender ? "Moi":name} - </strong>
                ${currentMessage.message}<br>
                <small>le ${date}</small>`  
                
            // go to end of page
            window.scrollTo(0, document.body.scrollHeight);
        }

    };
    setInterval(displayConv, 500);

    // Post
    async function postMessage(e) {
        e.preventDefault();
        if(messageInput.value.trim() != "") {
            let message = {
                'id_sender': `${userId}`,
                'id_conv': `<?= $_GET['conv'] ?>`,
                'message': messageInput.value
            }          
    
            await fetch('?page=sendmessage', {
                method: "POST",
                headers: {
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(message),
            })
            .catch(error => console.error("Error :", error));

            messageInput.value = "";
        }
    }    
    
    sendBtn.addEventListener('click', postMessage);
</script>