
<div class="row w-100">
<section class="col-4">
    <div class="text-bg-secondary z-0 h-100 w-100">
        <h4 class="px-4 py-3">Vos conversations</h4>
        <div class="px-2">

        </div>
    </div>
</section>
<section class="col-8">
    <div class="position-fixed px-4 py-3 z-3 w-100 text-bg-secondary">
        <h4 id="convTitle"></h4>
    </div>
    <div class="d-flex flex-column px-3" id="conv"></div>
    <div class="mt-3 px-3">
        <div class="form-floating">
            <textarea class="form-control" placeholder="Leave a comment here" id="message" name="message"></textarea>
            <label for="message">Votre message</label>
        </div>
        <button class="btn btn-success mt-2 mb-2" id="sendBtn">Envoyer</button>
    </div>
</section>




<script>
    // DOM var
    let convTitle = document.querySelector('#convTitle');
    let convBlock = document.querySelector('#conv');
    let messageInput = document.querySelector('#message');
    let sendBtn = document.querySelector('#sendBtn');

    // Data var
    const months = ['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];
    let conversation = [];

    // Display
    async function displayConv() {

        await fetch('?page=getconv&user=<?= $_SESSION['user_info']['id'] ?>&person=<?= $_GET['person']?>')
        .then(response => response.json())
        .then(data => conversation = data)
        .catch(error => console.error("Error :", error));
        
        convTitle.textContent = `Votre conversation avec ${conversation.friend.first_name} ${conversation.friend.last_name}`;

        while (conversation.messages.length > convBlock.children.length) {
            // Create card
            const card = document.createElement('div');
            convBlock.appendChild(card);
            card.classList.add('card','mb-2', `align-self-${conversation.user.id == conversation.messages[convBlock.children.length-1].id_sender ? 'end':'start'}`,`text-bg-${conversation.user.id == conversation.messages[convBlock.children.length-1].id_sender ? 'primary':'secondary'}`,'rounded-start','px-3','py-0');

            // Create card body
            const cardBody = document.createElement('div');
            cardBody.classList.add('card-body');
            card.appendChild(cardBody);

            // Create card content
            const cardContent = document.createElement('p');
            cardContent.classList.add('card-text');
            cardBody.appendChild(cardContent);
            let date = new Date(conversation.messages[convBlock.children.length-1].date_sent);
            date = `${date.getDate()} ${months[date.getMonth()]} ${date.getFullYear()} à ${date.getHours() < 10 ? "0":""}${date.getHours()}:${date.getMinutes() < 10 ? "0":""}${date.getMinutes()}`;
            cardContent.innerHTML = `
                <strong> ${conversation.user.id == conversation.messages[convBlock.children.length-1].id_sender ? "Moi":conversation.friend.first_name} - </strong>
                ${conversation.messages[convBlock.children.length-1].message}<br>
                <small>le ${date}</small>`  
                
            // go to end of page
            window.scrollTo(0, document.body.scrollHeight);
        }

    };
    setInterval(displayConv, 500);

    // Post
    async function postMessage(e) {
        e.preventDefault();
        if(messageInput.value.trim() != "") {
            let message = {
                'id_sender': "<?= $_SESSION['user_info']['id'] ?>",
                'id_receiver': "<?= $_GET['person'] ?>",
                'message': messageInput.value
            }          
    
            await fetch('?page=sendmessage', {
                method: "POST",
                headers: {
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(message),
            })
            .catch(error => console.error("Error :", error));

            messageInput.value = "";
        }
    }    
    sendBtn.addEventListener('click', postMessage);


</script>