<h2 class="text-center">Ajouter une image</h2>

<section class="w-75 m-auto">
    <form method="POST" class="">
        <div class="mb-3">
            <label for="src" class="form-label">Source</label>
            <input type="text" name="src" id="src" class="form-control" placeholder="Source">
        </div>
        <div class="mb-3">
            <label for="src" class="form-label">Titre</label>
            <input type="text" name="title" id="title" class="form-control" placeholder="Titre">
        </div>
        <div class="mb-3">
            <label for="author" class="form-label">Auteur</label>
            <input type="text" name="author" id="author" class="form-control" placeholder="Auteur">
        </div>
        <div class="mb-3">
            <label for="author_link" class="form-label">Lien auteur</label>
            <input type="text" name="author_link" id="author_link" class="form-control" placeholder="Lien auteur">
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <input type="text" name="description" id="description" class="form-control" placeholder="Description">
        </div>
        <input type="submit" name="submit" value="Envoyer" class="btn btn-secondary">
    </form>
</section>