<div class="container-fluid d-flex justify-content-between align-items-center mb-3">
    <a href="?page=details&id=<?= $image['id'] - 1 ?>" class="btn btn-secondary d-none d-md-block w-md-25" role="button">Image précédente</a>
    <h2 class="text-center w-100 w-md-50"><?= $image['title'] ?></h2>
    <a href="?page=details&id=<?= $image['id'] + 1 ?>" class="btn btn-secondary d-none d-md-block w-md-25" role="button"> Image suivante</a>
</div>

<section class="container-fluid mb-2">
    <div class="row mb-2">
        <!-- AFFICHAGE IMG -->
        <img src="<?= $image['src'] ?>" alt="<?= $image['title'] ?>" class="img-fluid col-12 col-md-6">

        <!-- AFFICHAGE INFOS -->
        <div class="col-12 col-md-6 px-md-3 py-3 py-md-0">
            <h5 class="">Plus d'informations</h5>
            <ul class="details__fiche list-unstyled">
                <li><strong>Description : </strong><?= $image['description'] ?></li>
                <li><strong>Artiste :</strong> <a href="<?= $image['author_link'] ?>" class="text-decoration-none text-secondary" target="_blank"><?= $image['author'] ?></a></li>
                <li><strong>Date de publication :</strong> <?= date_format(date_create($image['date_added']), "d/m/Y H:i") ?></li>
                <li><strong>Dernière modification :</strong> <?= date_format(date_create($image['date_updated']), "d/m/Y H:i")?></li>
                <li><strong>Posté par :</strong> <?= $image['id_user'] == NULL ? "Anonyme":$image['first_name'].' '.$image['last_name'] ?></li>
                <li><strong>Mentions j'aime :</strong> <?= $likes ?></li>
                <li>
                    <form method="post">
                        <input type="submit" name="like" class="btn btn-<?= $hasLiked['hasLiked'] == 0 ? "info":"secondary" ?> mt-2" value="<?= $hasLiked['hasLiked'] == 0 ? "J'aime":"Je n'aime plus" ?>">
                    </form>
                </li>
            </ul>
            <hr>

            <!-- AFFICHAGE COMMENTAIRES -->
            <h5>Commentaires (<?= sizeof($comments) ?>)</h5>
            <section class="mb-3">
                <?php foreach($comments as $comment) : ?>
                    <article class="mb-1">
                        <strong><?= $comment['first_name'].' '.$comment['last_name'] ?></strong>  
                        <span><?= $comment['comment'] ?></span>
                        <br><small>Posté le <?= date_format(date_create($comment['date_posted']), "d/m/Y à H:i")?>
                        <?php if(isset($_SESSION['user_info']) && $comment['id_user'] == $_SESSION['user_info']['id']) : ?>
                        - <a href="?page=details&id=<?= $image['id'] ?>&delete=<?= $comment['comment_id']?>" class="link-underline-opacity-10 link-secondary link-offset-3">Supprimer</a>
                        <?php endif ?>
                        </small>
                    </article>
                <?php endforeach ?>
            </section>

            <!-- FORMULAIRE COMMENTAIRE -->
            <?php if(isset($_SESSION['user_info'])) : ?>
                <form method="POST">
                    <div class="mb-2">
                        <textarea class="form-control" id="comment" rows="3" placeholder="Donnez-nous votre avis..." name="comment"></textarea>
                    </div>
                    <input type="submit" name="submit" class="btn btn-success">
                </form>
            <?php else : ?>
                <p class="text-danger">Vous devez être connecté·e pour poster un commentaire.</p>
            <?php endif ?>
        </div>
    </div>
    <a href="?page=gallery" class="btn btn-secondary">Retour galerie</a>
</section>

<script>
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>